[WIP] Image's placeholder for new document
VODGroup/VoiceOverDesigner pull request #112
Opened 2022-09-07 19:58 UTC by drucelweisse

# Description
This pr adds button on EditorView to open image file and save it to document. Add menu item to open file

## Changes:
- add NSButton to Editor storyboard, hooked it with addImageButtonTapped() function in EditorViewController

## Todo:
- [X] Create button "add image" that allows to select from Finder
- [ ] Add menu item for image attachment
- [ ] some tests?

## Screenshots
<img width="1540" alt="Screenshot 2022-09-07 at 22 58 10" src="https://user-images.githubusercontent.com/36012972/188965843-76a1334e-6a02-453e-b0ae-9f83945efa2b.png">

2022-09-10 18:46 UTC, drucelweisse commented
Added menu item interaction video sample

https://user-images.githubusercontent.com/36012972/189497408-ab85c547-6e86-4714-97b1-738d44242609.mov

2022-09-10 18:52 UTC, drucelweisse commented
Which file types should we support for image? Currently, panel will try to open any provided file.

2022-09-11 12:39 UTC, akaDuality requested changes

2022-09-11 12:39 UTC, akaDuality commented on VoiceOver Designer/Features/Sources/Editor/EditorViewController.swift
> +                    self?.presenter.update(image: image)
Can you extract openPanel-related and image setting code to separate functions? At this function we will have high-level code: request image and present image.

2022-09-11 12:39 UTC, akaDuality commented on VoiceOver Designer/Features/Sources/Editor/EditorViewController.swift
> +    // TODO: try to extract?
Support for menu is cool? Definitely I don't know where to place it :D 

This place is fine for know

2022-09-11 15:23 UTC, drucelweisse commented on VoiceOver Designer/Features/Sources/Editor/EditorViewController.swift
> +                    self?.presenter.update(image: image)
resolved in https://github.com/VODGroup/VoiceOverDesigner/pull/112/commits/92c28a0a6c7a18946663993a7f4b75a3efffd46f

2022-09-12 09:25 UTC, akaDuality approved these changes

2022-09-12 09:25 UTC, akaDuality commented on VoiceOver Designer/Features/Sources/Editor/EditorViewController.swift
> +            if let image = await requestImage() {
Async syntax is awesome!

2022-09-12 09:25 UTC, merged