Minor fixes
VODGroup/VoiceOverDesigner pull request #171
Opened 2023-01-01 15:56 UTC by akaDuality

2023-01-01 18:02 UTC, drucelweisse commented on Shared/Sources/Canvas/CanvasPresenter.swift
> +    func registeUndo(for action: Undoable) {
just typo

2023-01-01 18:12 UTC, drucelweisse requested changes
Loved how DocumentPresenter become shared entry point to manage controls. And an undoable protocol

2023-01-01 18:12 UTC, drucelweisse commented on VoiceOver Designer/Features/Tests/NavigatorTests/EmptyTests.swift
> +import Foundation
It seems to be an empty file or it doesn't have tests yet?

2023-01-02 09:55 UTC, akaDuality commented on VoiceOver Designer/Features/Tests/NavigatorTests/EmptyTests.swift
> +import Foundation
I moved all files out of this target, but a target can't exists without files inside. I had two ways: remove target at all or add missing file. I decide to keep target exists to simplify feature tests

2023-01-02 09:59 UTC, drucelweisse approved these changes

2023-01-02 09:59 UTC, merged