Image scale
VODGroup/VoiceOverDesigner pull request #215
Opened 2023-01-19 17:33 UTC by akaDuality

Managed image scale: AppKit knows about image's scale, but UIKit has no idea about that. As a result we should manage it by ourselves to keep controls aligned to image.

Also slightly prepares for feature `frames` when several images will be placed on board like figma. For know it allows to keep read-write code at single place for AppKit and UIKit.

2023-01-22 17:02 UTC, drucelweisse requested changes

2023-01-22 17:02 UTC, drucelweisse commented on VoiceOver Designer.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = P67Q4Q7HA9;
```suggestion
				DEVELOPMENT_TEAM = "";
```

2023-01-22 17:02 UTC, drucelweisse commented on VoiceOver Designer.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = P67Q4Q7HA9;
```suggestion
				DEVELOPMENT_TEAM = "";
```

2023-01-22 17:02 UTC, drucelweisse commented on VoiceOver Designer.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = P67Q4Q7HA9;
```suggestion
				DEVELOPMENT_TEAM = "";
```

2023-01-23 04:23 UTC, akaDuality commented
Have removed, thx!

2023-01-23 08:21 UTC, drucelweisse approved these changes

2023-01-23 08:21 UTC, merged