Add presentation mode prototype
VODGroup/VoiceOverDesigner pull request #271
Opened 2023-09-30 10:54 UTC by AgapovOne

Add presentation mode

<details><summary>Screenshots</summary>
<p>

<img width="3202" alt="Screenshot 2023-09-30 at 15 52 45" src="https://github.com/VODGroup/VoiceOverDesigner/assets/4246455/a186c5c3-b0cb-4f35-9b6f-e7001f988cce">

</p>
</details>

2023-10-15 18:16 UTC, akaDuality approved these changes

2023-10-15 18:16 UTC, akaDuality commented on VoiceOver Designer/Documents/WindowManager.swift
> +            return
Better to pass VODesignDocument and handle any inconvenience on the upper level

2023-10-15 20:02 UTC, akaDuality requested changes

2023-10-15 20:02 UTC, akaDuality commented on VoiceOver Designer/Features/Sources/Presentation/PresentationView.swift
> +            Color.clear
`imageSize` will be zero if there is no image

2023-10-15 20:02 UTC, akaDuality commented on VoiceOver Designer/Features/Sources/Presentation/PresentationView.swift
> +            Color.clear
Also, potential dividing by zero

2023-10-16 07:56 UTC, AgapovOne commented on VoiceOver Designer/Documents/WindowManager.swift
> +            return
Я думал не зависеть от VODesignDocument в протоколе, но в итоге стал зависеть в реализации. И смысл потеряло, да. Спасибо что заметил, исправил

2023-10-16 07:57 UTC, AgapovOne commented on VoiceOver Designer/Features/Sources/Presentation/PresentationView.swift
> +            Color.clear
No image is a valid case for any real document?
I see the possiblity in preview, but does it happen in real project?

2023-10-16 10:51 UTC, akaDuality commented on VoiceOver Designer/Features/Sources/Presentation/PresentationView.swift
> +            Color.clear
Not yet, but with artboards it will be possible case

2023-10-16 10:51 UTC, akaDuality commented on VoiceOver Designer/Features/Sources/Presentation/PresentationView.swift
> +            Color.clear
Not yet, but with artboards it will be possible case

2023-10-16 10:52 UTC, akaDuality commented on VoiceOver Designer/Features/Sources/Presentation/PresentationView.swift
> +            Color.clear
You can provide default size here

2023-10-16 11:01 UTC, AgapovOne commented on VoiceOver Designer/Features/Sources/Presentation/PresentationView.swift
> +    private func listButton(_ control: any AccessibilityView, index: Int) -> some View {
Caught an issue with indexes and containers here.
@akaDuality a question: is it fine that containers can have elements only 1 level deep?
Isn't it a recursive container that can have containers inside?

2023-10-16 11:03 UTC, akaDuality commented on VoiceOver Designer/Features/Sources/Presentation/PresentationView.swift
> +    private func listButton(_ control: any AccessibilityView, index: Int) -> some View {
Yeap, it's app's limitation.

I havn't check support for nested containers in VoiceOver

2023-10-16 18:11 UTC, AgapovOne commented on VoiceOver Designer/Features/Sources/Presentation/PresentationView.swift
> +            Color.clear
The only issue is division inside `minimalScaleFactor`, I checked in preview with 0 size.

Fixed it by adding guard in `minimalScaleFactor`

2023-10-16 18:14 UTC, AgapovOne commented
Current issues:

- id of AccessibilityView (#272)
- window resize on preview/editor toggle (non-critical)
- right sidebar breaks after one toggle to preview

2023-10-17 21:07 UTC, akaDuality commented
I see some constraint conflicts on main branch too, probably it breaks layout after presentation. Will investigate it

2023-10-17 22:29 UTC, akaDuality commented
Issue: when I toggle presentation a lot elements placed on canvas multiple times.
<img width="1164" alt="Screenshot 2023-10-17 at 19 28 37" src="https://github.com/VODGroup/VoiceOverDesigner/assets/3120680/c458685f-990b-450b-aac8-2bd7fa4f94a3">

If I would draw an element canvas update, but can't click on it and it wouldn't shown in left panel

2023-10-17 22:38 UTC, akaDuality commented
I'm going to investigate my issue

2023-10-18 01:37 UTC, akaDuality commented
Please, apply this patches in your branch, I've fixed problem with redrawing and responsiveness. 

[0001-Extract-PointerService.patch](https://github.com/VODGroup/VoiceOverDesigner/files/12974092/0001-Extract-PointerService.patch)
[0002-Refactor-subscriptions-subscribe-on-viewDidAppear.patch](https://github.com/VODGroup/VoiceOverDesigner/files/12974093/0002-Refactor-subscriptions-subscribe-on-viewDidAppear.patch)
[0003-Remove-controls-before-drawing.patch](https://github.com/VODGroup/VoiceOverDesigner/files/12974094/0003-Remove-controls-before-drawing.patch)

2023-10-18 01:38 UTC, akaDuality commented
As a result, everything should works fine

2023-10-18 04:44 UTC, AgapovOne commented
Looks great, bug

> right sidebar breaks after one toggle to preview (probably project controller reference breaks)

is gone. Let's merge?

id issue will be resolved later. Constraints are a different problem with project controller, not with presentation view.

UI for controls in presentation could be larger, but it should be another feature too)

2023-10-18 05:05 UTC, AgapovOne commented
Fixed constraints warnings in #275, they are not related to presentation mode

2023-10-18 19:30 UTC, AgapovOne commented
Current issue after window refinement: toolbar configuration after toggling presentation mode.

Some toolbar items should not be available for presentation mode, some should be hidden for editor mode.

2023-10-18 21:14 UTC, akaDuality approved these changes

2023-10-18 21:14 UTC, merged

2023-10-18 21:15 UTC, akaDuality commented
Congrats!

2023-10-18 21:15 UTC, akaDuality commented
Going to finish release with this brand new feature and add to credits on site