Preview on iPad with text description
VODGroup/VoiceOverDesigner pull request #291
Opened 2023-10-24 14:01 UTC by akaDuality

2023-10-26 06:55 UTC, AgapovOne commented
I pushed a fix for building, changed decision from phone to horizontalSizeClass.

But it still doesn't work for OTT samples

<details><summary>Details</summary>
<p>



</p>
</details>

2024-01-08 00:10 UTC, akaDuality commented on Shared/Sources/Presentation/PresentationView.swift
> +                        return Color(uiColor: control.color.withAlphaComponent(0.5)) // TODO: Is it fine for iOS?
Don't know what it better for iOS

2024-01-14 18:08 UTC, drucelweisse requested changes

2024-01-14 18:08 UTC, drucelweisse commented on Shared/Sources/ElementSettings/Components.swift
> +    @State var innerValue: String = ""
is it needed? seems to be unused

2024-01-14 18:08 UTC, drucelweisse commented on Shared/Sources/CommonUI/TextFieldOnSubmit.swift
> +    @FocusState private var isFocused: Bool
is private property needed? seems that focus is provided from parent.

If u really want to pass focus here you probably should pass FocusState<Bool>.Binding which is not the same thing as Binding<T>

2024-01-14 18:08 UTC, drucelweisse commented on VoiceOver Preview/VoiceOver Preview/BrowserViewController.swift
> +    func documentBrowser(_ controller: UIDocumentBrowserViewController, didPickDocumentsAt documentURLs: [URL]) {
why it's macrossed? do same thing as other function

2024-01-14 23:00 UTC, akaDuality commented on VoiceOver Preview/VoiceOver Preview/BrowserViewController.swift
> +    func documentBrowser(_ controller: UIDocumentBrowserViewController, didPickDocumentsAt documentURLs: [URL]) {
Nope, `didPickDocumentsAt` vs `didPickDocumentURLs`

2024-01-14 23:01 UTC, akaDuality commented on VoiceOver Preview/VoiceOver Preview/BrowserViewController.swift
> +    func documentBrowser(_ controller: UIDocumentBrowserViewController, didPickDocumentsAt documentURLs: [URL]) {
Who the fuck at Apple did this?

2024-01-14 23:05 UTC, akaDuality commented on Shared/Sources/CommonUI/TextFieldOnSubmit.swift
> +    @FocusState private var isFocused: Bool
It's the only way what I found to track lose of focus to publish change of `innerValue`

2024-01-14 23:12 UTC, merged