[WIP] Adjustable controls for Preview
VODGroup/VoiceOverDesigner pull request #30
Opened 2022-07-21 19:29 UTC by drucelweisse

# Description
This pr contains changes about adjustable controls for Preview App

## Changes

### Added:

- added VoiceOverElement: UIAccessibilityElement just to trigger adjustableOptions

#### AdjustableOptions
- Added currentValue: String? 
- Added accessibilityDecrement()
- Added accessibilityIncrement()

#### A11yDescription
- Added accessibilityDecrement()
- Added accessibilityIncrement()

### Changed
- changed PreviewViewController to show UIDocumentBrowserView if it's can't load document
- remove views from Main

# TODO

- [ ] Add UIImageView to display document image
- [ ] tests for all changes

# Related Issue
* #21

# Screenshots

There's none at the moment

2022-07-22 07:06 UTC, akaDuality requested changes

2022-07-22 07:06 UTC, akaDuality commented on VoiceOver Preview/VoiceOver Preview/PreviewViewController.swift
> +    override func accessibilityIncrement() {
It looks strange to implement `accessibilityIncrement` on a whole view. This function can be created only for `VoiceOverElement`

2022-07-22 07:06 UTC, akaDuality commented on VoiceOver Preview/VoiceOver Preview/VoiceOverElement.swift
> +    private func accessibilityElement(from control: A11yDescription) {
It would be better to call the function as `setup(from model: A11yDescription)`?

2022-07-22 07:06 UTC, akaDuality commented on VoiceOver Preview/VoiceOver Preview/PreviewViewController.swift
>          element.accessibilityTraits = control.trait.accessibilityTrait
This code is setup by VoiceOverElement themselves

2022-07-22 07:06 UTC, akaDuality commented on VoiceOver Preview/VoiceOver Preview/PreviewViewController.swift
> +    var focusedElement: UIAccessibilityElement? {
As a result there is no need to find focused element

2022-07-22 08:55 UTC, drucelweisse commented on VoiceOver Preview/VoiceOver Preview/PreviewViewController.swift
> +    override func accessibilityIncrement() {
yeah, it works, maybe I've been mislead at first glance

2022-07-22 08:56 UTC, drucelweisse commented on VoiceOver Preview/VoiceOver Preview/VoiceOverElement.swift
> +    private func accessibilityElement(from control: A11yDescription) {
Fixed in https://github.com/VODGroup/VoiceOverDesigner/pull/30/commits/de154c98ec0436c27b6ebd418e1b2ed1f4ed9d7c

2022-07-22 08:56 UTC, drucelweisse commented on VoiceOver Preview/VoiceOver Preview/PreviewViewController.swift
> +    var focusedElement: UIAccessibilityElement? {
Fixed in https://github.com/VODGroup/VoiceOverDesigner/pull/30/commits/de154c98ec0436c27b6ebd418e1b2ed1f4ed9d7c

2022-07-22 10:23 UTC, drucelweisse commented
added screen recording

2022-07-22 10:32 UTC, akaDuality commented
I've just discovered `[how to create system thumbnails](https://stackoverflow.com/questions/9165080/where-to-store-a-preview-of-a-uidocument)`

> using a NSFileWrapper as file format (where the document is actually a bundled folder) and save the preview within the document, as "Preview.jpg" (or .png) inside a folder labeled "QuickLook". This way, you'll get the preview in Finder on the Mac as well (for free).

2022-07-22 10:40 UTC, akaDuality commented
Have checked, it works when I press space for preview, not thumbnail

2022-07-22 12:01 UTC, drucelweisse commented
> Have checked, it works when I press space for preview, not thumbnail

Yeah, I figured out after this suggestion. Should document store Preview image separately from the main image? Maybe preview image will contain drawn controls?

2022-07-23 09:35 UTC, akaDuality commented
I prefer to see drawn elements to understand stage of a document

2022-07-24 11:29 UTC, akaDuality requested changes

2022-07-24 11:29 UTC, akaDuality commented on VoiceOver Preview/VoiceOver Preview.xcodeproj/project.pbxproj
> +		6BABB3552889BC5400FF259E /* CloudKit.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = 6BABB3542889BC5400FF259E /* CloudKit.framework */; };
What is CloudKit for?

2022-07-24 11:44 UTC, drucelweisse commented on VoiceOver Preview/VoiceOver Preview.xcodeproj/project.pbxproj
> +		6BABB3552889BC5400FF259E /* CloudKit.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = 6BABB3542889BC5400FF259E /* CloudKit.framework */; };
fixed in https://github.com/VODGroup/VoiceOverDesigner/pull/30/commits/8d14f5fde3c0fdf45d5a2d3c5d7ff452139b7301

2022-07-24 11:44 UTC, drucelweisse commented on VoiceOver Preview/VoiceOver Preview/PreviewViewController.swift
>          element.accessibilityTraits = control.trait.accessibilityTrait
change in https://github.com/VODGroup/VoiceOverDesigner/pull/30/commits/8d14f5fde3c0fdf45d5a2d3c5d7ff452139b7301

2022-07-24 11:54 UTC, akaDuality approved these changes

2022-07-24 13:33 UTC, merged