[WIP] Window management
VODGroup/VoiceOverDesigner pull request #42
Opened 2022-07-27 21:18 UTC by drucelweisse

# Description
This pr contains changes about window Management

## Changes

- Added EditorViewController static func makeWindow(for document: VODesingDocument) that creates new window
- removed use of ProjectsRouter, cause on remaking of new window controller loses it's router and don't open window,

## TODO:

- [X] Open Projects on document close
- [ ] Open Projects on dock click

## ScreenShots

https://user-images.githubusercontent.com/36012972/181374113-5f53a2ce-3856-43e0-8d3b-59df66dc11a2.mov

Help needed, to determine what event fired on dock click

2022-07-28 05:36 UTC, akaDuality commented
Probably we can terminate window when all windows close, the projects will open like app's restart.

AppDelegate:
```
public func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
   true
}
```

2022-07-28 16:06 UTC, drucelweisse commented
Yes, that worked

2022-07-28 18:12 UTC, akaDuality commented
Have you done the PR?

2022-07-28 18:16 UTC, akaDuality requested changes
Can we restore router to remove dependencies?

2022-07-28 18:16 UTC, akaDuality commented on VoiceOver Designer/Features/Package.swift
> +                "Editor"
Projects and Editor are feature-modules and shouldn't depend on each other

2022-07-28 18:16 UTC, akaDuality commented on VoiceOver Designer/Features/Sources/Projects/ProjectsViewController.swift
> -        router?.show(document: document)
Router was created to delegate to main app and remove dependencies between modules

2022-07-28 18:20 UTC, drucelweisse commented on VoiceOver Designer/Features/Sources/Projects/ProjectsViewController.swift
> -        router?.show(document: document)
Yeah, I've described it in pr, but for some reasons, on recreate projectsController it lost reference to WindowController as well router becomes nil.

I'll give it a new try :)

2022-07-28 19:01 UTC, akaDuality commented on VoiceOver Designer/Features/Sources/Projects/ProjectsViewController.swift
> -        router?.show(document: document)
I've discovered that Editor already depends on Settings. I'm going to fix it too

2022-07-28 19:02 UTC, akaDuality commented on VoiceOver Designer/Features/Sources/Projects/ProjectsViewController.swift
> -        router?.show(document: document)
We will keep router explicitly in AppDelegate. I can do it before tommorow

2022-07-28 19:04 UTC, akaDuality commented on VoiceOver Designer/Features/Sources/Projects/ProjectsViewController.swift
> -        router?.show(document: document)
I'll create some sort of main controller in the app's part, will show you a PR

2022-07-28 19:24 UTC, akaDuality commented on VoiceOver Designer/Features/Sources/Projects/ProjectsViewController.swift
> -        router?.show(document: document)
Check #44

2022-07-29 06:14 UTC, akaDuality commented
You can finish this PR without tests

2022-07-29 19:57 UTC, drucelweisse commented on VoiceOver Designer/Features/Package.swift
> +                "Editor"
resolved in https://github.com/VODGroup/VoiceOverDesigner/pull/42/commits/6d3e3129e96dffc2cd16f035efc92122423a7dec

2022-07-29 19:58 UTC, drucelweisse commented on VoiceOver Designer/Features/Sources/Projects/ProjectsViewController.swift
> -        router?.show(document: document)
resolved in https://github.com/VODGroup/VoiceOverDesigner/pull/42/commits/7e994525e931d06a04cac384a7c1647621e50dc3

2022-07-31 09:30 UTC, akaDuality commented
@drucelweisse I've rafactor to window delegate. Can you check the result?

2022-07-31 09:38 UTC, drucelweisse reviewed
Yeah, looks good and removes call to NSApplication shared instance

2022-07-31 11:12 UTC, merged