[WIP] 59 copy action when move element with pressed alt
VODGroup/VoiceOverDesigner pull request #69
Opened 2022-08-03 18:06 UTC by drucelweisse

# Description

this pr add copy action to A11yControl

## Changes
- Added new CopyAction: DraggingAction
- fixed typo in DraggingAction protocol
- Added keyListener in EditorViewController
- Changed DrawingController, EditorPresenter func mouseDown(on location: CGPoint) signature to mouseDown(on location: CGPoint, shouldCopy: Bool)

## Screenshots

https://user-images.githubusercontent.com/36012972/182678297-9f698c9b-9709-43d3-86a2-1408b62a4147.mov

2022-08-03 19:39 UTC, drucelweisse commented
Should I cover with test undo actions? I really don't know how to do it correctly

2022-08-04 05:36 UTC, akaDuality requested changes

2022-08-04 05:36 UTC, akaDuality commented on VoiceOver Designer/Features/Tests/EditorTests/EditorPresenterTests.swift
> +        sut.mouseDown(on: start10, shouldCopy: false)
It would be better to move default disabled flags to extension to not modify previous tests. Otherwise they will have a lot of useless parameters

2022-08-04 05:36 UTC, akaDuality commented on VoiceOver Designer/Features/Sources/Editor/EditorViewController.swift
> +        keyListener = NSEvent.addLocalMonitorForEvents(matching: [.flagsChanged], handler: { [weak self] event in
Can we create some wrapper like `AlingmentCommandModifier`? For example it can wrap translate and copy action, they have same interfaces and can be swap

2022-08-04 11:46 UTC, akaDuality commented
> Should I cover with test undo actions? I really don't know how to do it correctly

Yeah. Undo is tested at `VODesignDocumentUndoTests`. Can it help you? If no, I can checkout the branch and try by myself to show example

2022-08-04 11:48 UTC, drucelweisse commented
> > Should I cover with test undo actions? I really don't know how to do it correctly
> 
> Yeah. Undo is tested at `VODesignDocumentUndoTests`. Can it help you? If no, I can checkout the branch and try by myself to show example

Yes it will be helpful, just couldn't find it in project :)

2022-08-04 11:48 UTC, drucelweisse commented on VoiceOver Designer/Features/Sources/Editor/EditorViewController.swift
> +        keyListener = NSEvent.addLocalMonitorForEvents(matching: [.flagsChanged], handler: { [weak self] event in
I'll try to do that as well

2022-08-04 16:51 UTC, drucelweisse commented on VoiceOver Designer/Features/Tests/EditorTests/EditorPresenterTests.swift
> +        sut.mouseDown(on: start10, shouldCopy: false)
fixed in https://github.com/VODGroup/VoiceOverDesigner/pull/69/commits/87d14a321b3e308c95291dde9e167987c216f749

2022-08-06 15:15 UTC, drucelweisse commented
@akaDuality can you check it? I think I got wrong idea with CopyOptionModifier, probably last commit should be reverted or changed

2022-08-06 18:59 UTC, akaDuality commented
Going to check right now

2022-08-06 20:17 UTC, akaDuality commented
Have found a bug, fix tests and slightly renamed commands

2022-08-06 20:29 UTC, akaDuality requested changes

2022-08-06 20:29 UTC, akaDuality commented on Document/Sources/Document/Drawing/Actions/CopyAndTranslateAction.swift
> +//        sourceControl.updateWithoutAnimation {
Pls remove comments

2022-08-06 20:29 UTC, akaDuality commented on Document/Sources/Document/Drawing/Actions/CopyAndTranslateAction.swift
> +//        sourceControl.updateWithoutAnimation {
Also, copying can be done in A11yControl like `A11yDescription.copy(from: descriptionToCopy)`

2022-08-06 20:29 UTC, akaDuality commented on Document/Sources/Document/Drawing/Actions/CopyAndTranslateAction.swift
> +//        sourceControl.updateWithoutAnimation {
It remove unnecessary details makes your code more high-level in abstraction and

2022-08-06 20:29 UTC, akaDuality commented on Document/Sources/Document/Drawing/Actions/CopyAndTranslateAction.swift
> +    init(view: DrawingView, sourceControl: A11yControl, startLocation: CGPoint, offset: CGPoint, initialFrame: CGRect) {
Just idea: we can move this parameters to one `MoveParameter` object.

2022-08-06 20:29 UTC, akaDuality commented on VoiceOver Designer/Features/Tests/EditorTests/TranslatingTests.swift
> +    }
I've tried to test undo, but discovered that it combines it grouping levels by runloop cycle. Have no idea how to split yet.

<img width="916" alt="Screen Shot 2022-08-07 at 01 27 53" src="https://user-images.githubusercontent.com/3120680/183265086-b2902f4d-3469-4e6e-be87-b4763161dc00.png">

2022-08-06 20:35 UTC, akaDuality commented on VoiceOver Designer/Features/Tests/EditorTests/TranslatingTests.swift
> +    }
wow, moving `drawRect_10_60()` to `MainActor.run` solved the problem :-)

2022-08-06 20:44 UTC, drucelweisse commented on Document/Sources/Document/Drawing/Actions/CopyAndTranslateAction.swift
> +//        sourceControl.updateWithoutAnimation {
resolved in https://github.com/VODGroup/VoiceOverDesigner/pull/69/commits/d018dad5af2eb342bd69fc6d0713de72811360b1

2022-08-06 20:53 UTC, akaDuality commented
UIKitPreview is lost somewhere

2022-08-06 21:06 UTC, bbsody commented
Unfortunately, I can't build the project at the moment. Still, from what I can see in the attached video, the duplicated element doesn't appear in the left sidebar on the drag-end/mouse-up event, which is expected behaviour. As for the rest, great job here!

2022-08-06 21:08 UTC, akaDuality commented
@bbsody Reaction of left sidebar is fixed at #76 :-)

2022-08-07 13:32 UTC, akaDuality approved these changes

2022-08-07 13:32 UTC, merged